spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      function:
        definition: enrichEmployee
      bindings:
        enrichEmployee-in-0:
          destination: test_EMPLOYEE
          contentType: application/*+avro
          consumer:
            use-native-decoding: true
        enrichEmployee-in-1:
          destination: test_DEPARTMENT
          contentType: application/*+avro
          consumer:
            use-native-decoding: true
        enrichEmployee-out-0:
          destination: test_RESULT
          contentType: application/*+avro
          producer:
            use-native-encoding: true
      kafka:
        streams:
          binder:
            brokers:
              - localhost:9092
            functions:
              enrichEmployee.applicationId: 175594_appid
            configuration:
              specific.avro.reader: true
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              state.dir: state-store
              acceptable.recovery.lag: 0
              schema.registry.url: http://localhost:8081
          bindings:
            enrichEmployee-in-0:
              consumer:
                configuration:
                  key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                  value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                  specific.avro.reader: true
            enrichEmployee-in-1:
              consumer:
                configuration:
                  key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                  value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                  specific.avro.reader: true
            enrichEmployee-out-0:
              producer:
                configuration:
                  key.serializer: org.apache.kafka.common.serialization.StringSerializer
                  value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                  specific.avro.reader: true
                useNativeEncoding: true
        binder:
          configuration:
            heartbeat.interval.ms: 10000
            max.poll.records: 5000


#logging:
#  level:
#    root: DEBUG