spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      function:
        definition: supplier
      bindings:
        supplier-out-0:
          contentType: application/*+avro
          destination: test_DEPARTMENT
          producer:
            useNativeEncoding: true
      kafka:
        bindings:
          supplier-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                schema.registry.url: http://localhost:8081
        binder:
          brokers:
            - localhost:9092
      schema-registry-client:
        endpoint: http://localhost:8081
      schema:
        avro:
          schema-locations: classpath:avro/department-schema.avsc
#logging:
#  level:
#    ROOT: DEBUG